version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: fareedzaman501
      MONGO_INITDB_ROOT_PASSWORD: fareedzaman501

volumes:
  mongodb_data:
